function servicePageBody(name: string): string {
  return `<p>DSB Law Group advises clients on <strong>${name}</strong> — regulatory compliance, documentation, dispute resolution, and strategic counsel tailored to your business.</p>
<p>Contact us to discuss your requirements or subscribe to ${name.toLowerCase()} updates via our newsletter.</p>`;
}

const SERVICE_CATEGORY_PAGES = [
  { slug: 'intellectual-property', name: 'Intellectual Property Rights' },
  { slug: 'labour-law', name: 'Labor & Industrial Law' },
  { slug: 'joint-ventures', name: 'Joint Ventures' },
  { slug: 'taxation', name: 'Taxation' },
  { slug: 'business-advisory', name: 'Business Advisory' },
  { slug: 'banking-finance', name: 'Banking & Finance' },
  { slug: 'private-equity', name: 'Private Equity' },
  { slug: 'audit', name: 'Audit' },
  { slug: 'mergers-acquisitions', name: 'Mergers & Acquisitions' },
  { slug: 'corporate-advisory', name: 'Corporate Advisory' },
].map((cat) => ({
  slug: cat.slug,
  title: cat.name,
  body: servicePageBody(cat.name),
  metaTitle: `${cat.name} | DSB Law Group`,
  metaDescription: `${cat.name} legal advisory and compliance services from DSB Law Group.`,
  metaKeywords: `${cat.slug.replace(/-/g, ', ')}, DSB Law, legal services`,
}));

const CMS_PAGES = [
  {
    slug: 'about',
    title: 'About DSB Law Group',
    body: '<p>DSB Law Group is a full-service Indian law firm offering legal and business solutions across banking, NBFC regulations, corporate law, taxation, audit, and strategic advisory.</p><p>Founded in 1967, we serve clients pan India from eleven offices.</p>',
    metaTitle: 'About Us',
    metaDescription: 'About DSB Law Group — legal advisory and corporate services.',
    metaKeywords: 'DSB Law, about us, legal firm',
  },
  {
    slug: 'achievements',
    title: 'Achievements',
    body: '<p>DSB Law Group has been recognized for regulatory excellence, client retention, and award-winning advisory across banking, NBFC, and corporate mandates.</p><p>Content can be updated here from the admin panel.</p>',
    metaTitle: 'Achievements',
    metaDescription: 'Awards and milestones — DSB Law Group.',
    metaKeywords: 'achievements, awards, DSB Law',
  },
  {
    slug: 'nbfc',
    title: 'NBFC',
    body: '<p>End-to-end NBFC consultancy — licensing, incorporation, funding, investor tie-ups, and RBI compliance advisory.</p><p>DSB Law Group has supported 50+ NBFC establishments across India.</p>',
    metaTitle: 'NBFC Consultancy',
    metaDescription: 'NBFC licensing, governance, and regulatory advisory.',
    metaKeywords: 'NBFC, RBI, licensing, compliance',
  },
  {
    slug: 'ucbs',
    title: "UCB's",
    body: '<p>Advisory for Urban Cooperative Banks — governance, RBI compliance, audits, and regulatory submissions.</p>',
    metaTitle: "UCB's — Urban Cooperative Banks",
    metaDescription: 'Urban Cooperative Bank regulatory and legal advisory.',
    metaKeywords: 'UCB, cooperative bank, RBI',
  },
  {
    slug: 'hr-labour-laws',
    title: 'HR & Labour Laws',
    body: '<p>Advisory on employment law, industrial disputes, and HR compliance programmes.</p><p>See also our dedicated <a href="/pages/labour-law">Labor &amp; Industrial Law</a> practice page.</p>',
    metaTitle: 'HR & Labour Laws',
    metaDescription: 'Labour and industrial law advisory services.',
    metaKeywords: 'labour law, HR compliance, industrial law',
  },
  {
    slug: 'about-hr-labour-law',
    title: 'About HR & Labour Law',
    body: '<p>Overview of DSB Law Group&apos;s HR and labour law practice — workforce structuring, disputes, POSH, and code compliance.</p>',
    metaTitle: 'About HR & Labour Law',
    metaDescription: 'HR and labour law practice overview.',
    metaKeywords: 'HR, labour law, employment',
  },
  {
    slug: 'new-labour-codes-compliance',
    title: 'New Labour Codes Compliance',
    body: '<p>Guidance on India&apos;s new labour codes — compliance roadmaps, policy updates, and employer obligations.</p>',
    metaTitle: 'New Labour Codes Compliance',
    metaDescription: 'Labour code compliance advisory for employers.',
    metaKeywords: 'labour codes, compliance, HR',
  },
  {
    slug: 'dinesh-gupta',
    title: 'Dinesh Gupta & Co.',
    body: '<p>Dinesh Gupta &amp; Co. is associated with DSB Law Group, providing integrated financial, legal, and corporate advisory.</p><p>Profile content can be edited from the admin CMS.</p>',
    metaTitle: 'Dinesh Gupta & Co.',
    metaDescription: 'Dinesh Gupta & Co. — DSB Law Group.',
    metaKeywords: 'Dinesh Gupta, Dinesh Gupta and Co',
  },
  {
    slug: 'research',
    title: 'Research',
    body: '<p>Research publications and regulatory commentary from DSB Law Group.</p>',
    metaTitle: 'Research',
    metaDescription: 'Legal and regulatory research — DSB Law Group.',
    metaKeywords: 'research, publications, legal',
  },
  {
    slug: 'podcasts',
    title: 'Podcasts',
    body: '<p>Podcast episodes and audio insights from DSB Law Group advisors.</p>',
    metaTitle: 'Podcasts',
    metaDescription: 'DSB Law Group podcasts.',
    metaKeywords: 'podcasts, audio, legal insights',
  },
  {
    slug: 'video-lectures',
    title: 'Video Lectures',
    body: '<p>Video lectures and webinars on banking, NBFC, taxation, and corporate law topics.</p>',
    metaTitle: 'Video Lectures',
    metaDescription: 'Video lectures and webinars — DSB Law Group.',
    metaKeywords: 'video, webinars, lectures',
  },
  {
    slug: 'disclaimer',
    title: 'Disclaimer',
    body: '<p>This website is for general information only and does not constitute legal advice. Contact DSB Law Group for advice specific to your situation.</p>',
    metaTitle: 'Disclaimer',
    metaDescription: 'Website disclaimer — DSB Law Group.',
    metaKeywords: 'disclaimer',
  },
  {
    slug: 'privacy',
    title: 'Privacy Policy',
    body: '<p>Our privacy policy describes how we collect, use, and protect your personal information.</p>',
    metaTitle: 'Privacy Policy',
    metaDescription: 'DSB Law Group privacy policy.',
    metaKeywords: 'privacy policy',
  },
  {
    slug: 'terms',
    title: 'Terms & Conditions',
    body: '<p>Terms governing use of this website and our services.</p>',
    metaTitle: 'Terms & Conditions',
    metaDescription: 'Website terms and conditions.',
    metaKeywords: 'terms and conditions',
  },
  {
    slug: 'careers',
    title: 'Career Opportunities',
    body: '<p>Join DSB Law Group — send your CV via the contact form with the subject Careers.</p>',
    metaTitle: 'Careers',
    metaDescription: 'Career opportunities at DSB Law Group.',
    metaKeywords: 'careers, jobs, legal careers',
  },
  ...SERVICE_CATEGORY_PAGES,
];

export { CMS_PAGES, SERVICE_CATEGORY_PAGES };
